### ISSUE TITLE
Readme contains incorrect method names

### ISSUE THREAD

**Issue by freddieline** [dividohq/merchant-api-pub-sdk-php#9]
$response = $sdk->application_refunds()->createApplicationRefund($application, $applicationRefund);

SHOULD BE

$response = $sdk->applicationRefunds()->createApplicationRefund($application, $applicationRefund);

AND

$response = $sdk->application_activations()->createApplicationActivation($application, $applicationActivation);

SHOULD BE 

$response = $sdk->applicationActivations()->createApplicationActivation($application, $applicationActivation);

**Comment by JonnyCarter** [comment]
Fixed
